version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  # mailcatcher:
  #   image: yappabe/mailcatcher
  #   ports:
  #       - 1025:1025
  #       - 1080:1080
  # redis:
  #   image: 'redis:3.2-alpine'
  #   command: redis-server
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      # - 'redis'
      # - 'mailcatcher'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/onebnb_api'
    env_file:
      - '.env'

  # cable:
  #   depends_on:
  #     - 'redis'
  #   build: .
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'
  #   volumes:
  #     - '.:/onebnb_api'
  #   env_file:
  #     - '.env'

volumes:
  # redis:
  postgres:

# dbdata:
#   image: postgres:9.4.10
#   volumes:
#     - /var/lib/postgresql/data
#   command: "true"

# db:
#   image: postgres:9.4.10
#   volumes_from:
#     - dbdata
#   ports:
#     - "5432:5432"
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: conecta

# mailcatcher:
#   image: yappabe/mailcatcher
#   ports:
#     - "1025:1025"
#     - "1080:1080"
# esdata:
#   image: elasticsearch:1.3
#   volumes:
#     - /usr/share/elasticsearch/data
#   command: "true"

# es:
#   image: elasticsearch:1.3
#   volumes_from:
#     - esdata
#   ports:
#     - "9200:9200"
#     - "9300:9300"
