---
development:
  cloud_name: dgekdykfj
  api_key: '237614898178736'
  api_secret: BqAZcHSYNDJzL3LjD0s_OhIo-1A
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dgekdykfj
  api_key: '237614898178736'
  api_secret: BqAZcHSYNDJzL3LjD0s_OhIo-1A
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dgekdykfj
  api_key: '237614898178736'
  api_secret: BqAZcHSYNDJzL3LjD0s_OhIo-1A
  enhance_image_tag: true
  static_image_support: false
